steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/payments-ui/payments-ui:$COMMIT_SHA',
        '.'
      ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/payments-ui/payments-ui:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

